#!/bin/bash

blue="\e[34m"
cyan="\e[36m"
yellow="\e[33m"
default="\e[39m"

if (( $EUID != 0 ))
then
    sudo clean
else
    echo -e     "${blue}+--------------------------------------+"
    echo -e "|${default}            Cleaning up...            ${blue}|"
    echo               "+--------------------------------------+"
    echo -e ">>>${default} ${yellow}sudo ${cyan}apt-get autoremove${default}"
    if ! sudo apt-get autoremove
    then
        for i in 1 2 3; do echo && printf "Retrying..." && sleep 5s && echo && sudo apt-get autoremove && break; done
    fi
    echo
    echo -e "${blue}>>>${default} ${yellow}sudo ${cyan}apt-get autoclean${default}"
    if ! sudo apt-get autoclean
    then
        for i in 1 2 3; do echo && printf "Retrying..." && sleep 5s && echo && sudo apt-get autoclean && break; done
    fi
    echo
    echo -e "${blue}>>>${default} ${yellow}sudo ${cyan}apt-get clean${default}"
    if sudo apt-get clean
    then
        echo "Done"
    else
        for i in 1 2 3; do echo && printf "Retrying..." && sleep 5s && echo && sudo apt-get clean && echo "Done" && break; done
    fi
    echo
    echo -e  "${blue}#======================================#"
    echo -e "$default       System Clean up completed!       ${blue}"
    echo -e         "#======================================#$default"
fi
