#!/bin/bash

blue="\e[34m"
cyan="\e[36m"
yellow="\e[33m"
default="\e[39m"

if (( $EUID != 0 ))
then
    sudo update
else
    echo -e     "${blue}+--------------------------------------+"
    echo -e "|${default}  Checking for Update and upgrade...  ${blue}|"
    echo               "+--------------------------------------+"
    echo -e ">>>${default} ${yellow}sudo ${cyan}apt-get update${default}"
    if ! sudo apt-get update
    then
        for i in 1 2 3; do echo && printf "Retrying..." && sleep 5s && echo && sudo apt-get update && break; done
    fi
    echo
    echo -e "${blue}>>>${default} ${yellow}sudo ${cyan}apt-get upgrade${default}"
    if ! sudo apt-get upgrade
    then
        for i in 1 2 3; do echo && printf "Retrying..." && sleep 5s && echo && sudo apt-get upgrade && break; done
    fi
    echo
    echo -e "${blue}>>>${default} ${yellow}sudo ${cyan}apt-get dist-upgrade${default}"
    if ! sudo apt-get dist-upgrade
    then
        for i in 1 2 3; do echo && printf "Retrying..." && sleep 5s && echo && sudo apt-get dist-upgrade && break; done
    fi
    echo 
    echo -e      "$blue#======================================#"
    echo -e "${default}       Your system is up to date!       $blue"
    echo -e           "#======================================#$default"
fi
