#!/bin/bash

pause()
{
    echo
    secs=3
    while [ $secs -ge 0 ]; do
        sleep 1
        echo -ne "[Clean up start in ${secs}s please wait...]\033[0K\r"
        : $((secs--))
    done
    echo
}

update && pause && clean
